"""Infrastructure configuration exports."""

from typing import Any

from houyi.infrastructure.config.env_config import (
    ENV_CHAT_DATA_DIR,
    ENV_CHAT_SETTINGS_PATH,
    ENV_CHAT_SYSTEM_PROMPT,
    ENV_CHAT_TOOL_LOOP_MAX_MESSAGE_CHARS,
    ENV_CHAT_TOOL_LOOP_MAX_TOTAL_CHARS,
    ENV_DEEPSEEK_MODEL,
    ENV_DEFAULT_LLM_PROVIDER,
    ENV_EMBEDDING_MODEL,
    ENV_EMBEDDING_PROVIDER,
    ENV_EXECUTION_BACKEND,
    ENV_FRESH_REPLAY_USE_TOOL_CACHE,
    ENV_FRESH_REPLAY_USE_WEB_SEARCH_CACHE,
    ENV_GEMINI_MODEL,
    ENV_GOOGLE_API_KEY,
    ENV_GOOGLE_APPLICATION_CREDENTIALS,
    ENV_GOOGLE_CLOUD_PROJECT,
    ENV_HOUYI_PORT,
    ENV_KNOWLEDGE_STORAGE,
    ENV_OPENAI_API_KEY,
    ENV_OPENAI_BASE_URL,
    ENV_RESEARCH_MAX_AGENTS,
    ENV_RESEARCH_ORCHESTRATION_MODE,
    ENV_SILICONFLOW_API_KEY,
    ENV_SILICONFLOW_BASE_URL,
    ENV_TOOLCALL_ADAPTER,
    ENV_TOOLCALL_FAST_PATH,
    ENV_TOOLCALL_LOOP_MAX_MESSAGE_CHARS,
    ENV_TOOLCALL_LOOP_MAX_TOTAL_CHARS,
    ENV_TOOLCALL_MAX_PARALLEL_CALLS,
    ENV_TOOLCALL_MAX_RETRIES,
    ENV_TOOLCALL_MAX_TOKENS,
    ENV_TOOLCALL_MODEL,
    ENV_TOOLCALL_RESULT_SUMMARY_ENABLED,
    ENV_TOOLCALL_RESULT_SUMMARY_MAX_CHARS,
    ENV_TOOLCALL_RESULT_SUMMARY_MAX_ITEMS,
    ENV_TOOLCALL_TIMEOUT,
    ENV_TOOLCALL_TIMING,
    ENV_TOOLCALL_TOOL_LATENCY_MS,
    EnvConfig,
)


class _LazyEnv:
    """Lazy proxy that defers EnvConfig initialization until first attribute access."""

    def __getattr__(self, name: str) -> Any:
        return getattr(EnvConfig.get(), name)

    def __repr__(self) -> str:
        return repr(EnvConfig.get())


env: EnvConfig = _LazyEnv()  # type: ignore[assignment]

__all__ = [
    "ENV_CHAT_DATA_DIR",
    "ENV_CHAT_SETTINGS_PATH",
    "ENV_CHAT_SYSTEM_PROMPT",
    "ENV_CHAT_TOOL_LOOP_MAX_MESSAGE_CHARS",
    "ENV_CHAT_TOOL_LOOP_MAX_TOTAL_CHARS",
    "ENV_DEEPSEEK_MODEL",
    "ENV_DEFAULT_LLM_PROVIDER",
    "ENV_EMBEDDING_MODEL",
    "ENV_EMBEDDING_PROVIDER",
    "ENV_EXECUTION_BACKEND",
    "ENV_FRESH_REPLAY_USE_TOOL_CACHE",
    "ENV_FRESH_REPLAY_USE_WEB_SEARCH_CACHE",
    "ENV_GEMINI_MODEL",
    "ENV_GOOGLE_API_KEY",
    "ENV_GOOGLE_APPLICATION_CREDENTIALS",
    "ENV_GOOGLE_CLOUD_PROJECT",
    "ENV_HOUYI_PORT",
    "ENV_KNOWLEDGE_STORAGE",
    "ENV_OPENAI_API_KEY",
    "ENV_OPENAI_BASE_URL",
    "ENV_RESEARCH_MAX_AGENTS",
    "ENV_RESEARCH_ORCHESTRATION_MODE",
    "ENV_SILICONFLOW_API_KEY",
    "ENV_SILICONFLOW_BASE_URL",
    "ENV_TOOLCALL_ADAPTER",
    "ENV_TOOLCALL_FAST_PATH",
    "ENV_TOOLCALL_LOOP_MAX_MESSAGE_CHARS",
    "ENV_TOOLCALL_LOOP_MAX_TOTAL_CHARS",
    "ENV_TOOLCALL_MAX_PARALLEL_CALLS",
    "ENV_TOOLCALL_MAX_RETRIES",
    "ENV_TOOLCALL_MAX_TOKENS",
    "ENV_TOOLCALL_MODEL",
    "ENV_TOOLCALL_RESULT_SUMMARY_ENABLED",
    "ENV_TOOLCALL_RESULT_SUMMARY_MAX_CHARS",
    "ENV_TOOLCALL_RESULT_SUMMARY_MAX_ITEMS",
    "ENV_TOOLCALL_TIMEOUT",
    "ENV_TOOLCALL_TIMING",
    "ENV_TOOLCALL_TOOL_LATENCY_MS",
    "EnvConfig",
    "env",
]
