"""Deep Research engine — plan, search, aggregate, report."""

from houyi.application.research.aggregator import SourceAggregator
from houyi.application.research.planner import ResearchPlanner
from houyi.application.research.quality import QualityEvaluator
from houyi.application.research.report import ReportGenerator
from houyi.application.research.runtime import ResearchRuntime
from houyi.application.research.runtime.search import SearchCoordinator
from houyi.application.research.types import (
    AggregatedSources,
    Citation,
    ExportFormat,
    FACTScore,
    OrchestrationMode,
    OutlineSection,
    PlanEdit,
    PlanEditOperation,
    PlanStatus,
    QualityDetail,
    QualityScore,
    RACEScore,
    ReportChunk,
    ReportChunkType,
    ReportMetadata,
    ReportSection,
    ReportStyle,
    ResearchDepth,
    ResearchPlan,
    ResearchProgress,
    ResearchReport,
    ResearchSettings,
    ResearchStatus,
    SearchContext,
    SearchHit,
    SearchResult,
    SearchRound,
    SearchStrategy,
    SourceReference,
    SubQuestion,
)

__all__ = [
    "AggregatedSources",
    "Citation",
    "ExportFormat",
    "FACTScore",
    "OrchestrationMode",
    "OutlineSection",
    "PlanEdit",
    "PlanEditOperation",
    "PlanStatus",
    "QualityDetail",
    "QualityEvaluator",
    "QualityScore",
    "RACEScore",
    "ReportChunk",
    "ReportChunkType",
    "ReportGenerator",
    "ReportMetadata",
    "ReportSection",
    "ReportStyle",
    "ResearchDepth",
    "ResearchPlan",
    "ResearchPlanner",
    "ResearchProgress",
    "ResearchReport",
    "ResearchRuntime",
    "ResearchSettings",
    "ResearchStatus",
    "SearchContext",
    "SearchCoordinator",
    "SearchHit",
    "SearchResult",
    "SearchRound",
    "SearchStrategy",
    "SourceAggregator",
    "SourceReference",
    "SubQuestion",
]
